# Generated by Django 6.0.6 on 2026-07-01 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(blank=True, max_length=50, verbose_name='Matricule')),
                ('position', models.CharField(blank=True, max_length=150, verbose_name='Poste')),
                ('contract_end_date', models.DateField(blank=True, null=True, verbose_name='Fin de contrat')),
                ('photo', models.FileField(blank=True, null=True, upload_to='profiles/')),
                ('role', models.CharField(choices=[('user', 'Employe'), ('admin', 'Admin'), ('superadmin', 'Super admin')], default='user', max_length=20)),
                ('leave_balance', models.DecimalField(decimal_places=1, default=30, max_digits=6, verbose_name='Solde de conge')),
                ('recovery_balance', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='Solde de recuperation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil employe',
                'verbose_name_plural': 'Profils employes',
                'ordering': ['user__first_name', 'user__last_name', 'user__username'],
            },
        ),
    ]
