# Generated by Django 6.0.6 on 2026-07-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_contracttype_department_project_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='portal',
            field=models.CharField(choices=[('employee', 'Employe'), ('admin', 'Ressource Humain (RH)')], default='employee', max_length=20),
        ),
    ]
