# Generated by Django 6.0.6 on 2026-07-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_department_alter_employeeprofile_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('consultant', 'Consultant'), ('temporary', 'Temporaire')], default='', max_length=20, verbose_name='Type de contrat'),
        ),
    ]
