# Generated by Django 6.0.6 on 2026-07-22 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_alter_role_portal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='leave_balance',
        ),
        migrations.CreateModel(
            name='AnnualLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Annee')),
                ('quota', models.DecimalField(decimal_places=1, default=30, max_digits=6, verbose_name='Quota')),
                ('consumed', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='Consomme')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Bloque')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_leaves', to='personnel.employeeprofile', verbose_name='Employe')),
            ],
            options={
                'verbose_name': 'Conge annuel',
                'verbose_name_plural': 'Conges annuels',
                'ordering': ['year'],
                'unique_together': {('employee', 'year')},
            },
        ),
    ]
