# Generated by Django 6.0.6 on 2026-07-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0004_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='role',
            field=models.CharField(choices=[('user', 'Employe'), ('admin', 'Admin'), ('hierarchical', 'Chef hierarchique'), ('direction', 'Direction')], default='user', max_length=20),
        ),
    ]
