# Generated by Django 6.0.6 on 2026-08-20 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0004_annual_leave_window'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualRecovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Annee')),
                ('balance', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='Solde')),
                ('consumed', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='Consomme')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_recoveries', to='personnel.employeeprofile', verbose_name='Employe')),
            ],
            options={
                'verbose_name': 'Recuperation annuelle',
                'verbose_name_plural': 'Recuperations annuelles',
                'ordering': ['year'],
                'unique_together': {('employee', 'year')},
            },
        ),
    ]
