"""
Custom logging handler that stores log entries in the database.

This handler bridges the existing file-based Python logging system with the
LogEntry model, allowing the RH logs interface to display structured log
entries alongside the error IDs generated by the error-handling middleware.
"""
import logging
import json
import re
from datetime import datetime

from django.utils import timezone


ERR_ID_PATTERN = re.compile(r'ERR-\d{8}-[A-F0-9]+')


class DatabaseLogHandler(logging.Handler):
    """
    A logging handler that persists LogEntry records to the database.

    This handler is wired to the 'application' logger so that every log
    emitted through ``logger = logging.getLogger("application")`` is also
    stored in the ``administration_logentry`` table.

    The existing file-based handlers (``application_file`` and ``error_file``)
    continue to write to their log files — this handler simply mirrors
    application-level log records into the database for querying.
    """

    def emit(self, record):
        try:
            self._write_to_db(record)
        except Exception:
            # Never let logging errors break the request/response cycle.
            self.handleError(record)

    def _write_to_db(self, record):
        from apps.administration.models import LogEntry
        from apps.error_handling.middleware import _get_request_context

        message = record.getMessage()

        level_map = {
            logging.INFO: LogEntry.LEVEL_INFO,
            logging.WARNING: LogEntry.LEVEL_WARNING,
            logging.ERROR: LogEntry.LEVEL_ERROR,
            logging.CRITICAL: LogEntry.LEVEL_CRITICAL,
        }
        level = level_map.get(record.levelno, LogEntry.LEVEL_INFO)

        ctx = _get_request_context()

        error_id = ""
        match = ERR_ID_PATTERN.search(message)
        if match:
            error_id = match.group(0)

        user = None
        user_display = ""
        if ctx.get("user"):
            user = ctx["user"]
            user_display = getattr(user, "username", "")

        extra_data = {}
        if hasattr(record, "extra_data"):
            extra_data = getattr(record, "extra_data")
        elif record.exc_info:
            extra_data = {"has_exception": True}

        LogEntry.objects.create(
            level=level,
            logger_name=record.name,
            message=message,
            user=user,
            user_display=user_display,
            request_path=ctx.get("path", ""),
            request_method=ctx.get("method", ""),
            request_ip=ctx.get("ip", ""),
            error_id=error_id,
            exception_type=record.exc_info[0].__name__ if record.exc_info and record.exc_info[0] else "",
            traceback_data=self._format_traceback(record),
            extra_data=extra_data,
        )

    def _format_traceback(self, record):
        if record.exc_info:
            import traceback
            return "".join(traceback.format_exception(*record.exc_info))
        return getattr(record, "traceback_data", "") or ""
