# Generated by Django 6.0.6 on 2026-07-01 11:32

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('leave', 'Conge'), ('absence', 'Absence'), ('recovery', 'Recuperation')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumise'), ('approved', 'Approuvee'), ('rejected', 'Rejetee')], default='submitted', max_length=20)),
                ('project_name', models.CharField(blank=True, max_length=150, verbose_name='Projet')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Date debut')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date fin')),
                ('total_days', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='Total jours')),
                ('remaining_days_for_reason', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='Jours restants pour le motif')),
                ('reason', models.TextField(blank=True, verbose_name='Motif')),
                ('admin_comment', models.TextField(blank=True, verbose_name='Commentaire admin')),
                ('hierarchical_signature', models.CharField(blank=True, max_length=120)),
                ('administration_signature', models.CharField(blank=True, max_length=120)),
                ('direction_signature', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='personnel.employeeprofile')),
            ],
            options={
                'verbose_name': 'Demande',
                'verbose_name_plural': 'Demandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecoveryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(verbose_name='Date')),
                ('work_description', models.CharField(max_length=255, verbose_name='Nature de travaux')),
                ('start_time', models.TimeField(verbose_name='Debut heure')),
                ('end_time', models.TimeField(verbose_name="Fin d'heure")),
                ('duration_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Duree')),
                ('initials', models.CharField(blank=True, max_length=120, verbose_name='Emargement')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_lines', to='requests_management.staffrequest')),
            ],
            options={
                'verbose_name': 'Ligne de recuperation',
                'verbose_name_plural': 'Lignes de recuperation',
                'ordering': ['work_date', 'start_time'],
            },
        ),
    ]
