# Generated by Django 6.0.6 on 2026-07-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_management', '0002_recoveryline_is_holiday_remove_initials'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffrequest',
            name='approval_stage',
            field=models.CharField(choices=[('hierarchy', 'Chef hierarchique'), ('administration', 'Administration'), ('direction', 'Direction'), ('completed', 'Terminee')], default='hierarchy', max_length=20, verbose_name="Etape d'approbation"),
        ),
    ]
