# Generated by Django 6.0.6 on 2026-07-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_management', '0003_staffrequest_approval_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumise'), ('approved', 'Approuvee'), ('rejected', 'Rejetee'), ('cancelled', 'Annulee')], default='submitted', max_length=20),
        ),
    ]
