# Generated by Django 6.0.6 on 2026-07-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_management', '0005_staffrequest_start_time_staffrequest_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffrequest',
            name='approval_stage',
            field=models.CharField(choices=[('hierarchy', 'Chef hierarchique'), ('administration', 'Ressource Humain (RH)'), ('direction', 'Direction'), ('completed', 'Terminee')], default='hierarchy', max_length=20, verbose_name="Etape d'approbation"),
        ),
    ]
