# Generated by Django 6.0.6 on 2026-07-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_management', '0006_alter_staffrequest_approval_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffrequest',
            name='leave_consumption',
            field=models.JSONField(blank=True, default=dict, help_text='Exemple: {"2024": 5, "2025": 3} - utilise pour le restaur', verbose_name='Repartition conge par annee'),
        ),
    ]
