# Generated by Django 6.0.6 on 2026-08-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_management', '0007_staffrequest_leave_consumption'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffrequest',
            name='recovery_consumption',
            field=models.JSONField(blank=True, default=dict, help_text='Exemple: {"2024": 5, "2025": 3} - utilise pour le restaur', verbose_name='Repartition recuperation par annee'),
        ),
    ]
