# Generated by Django 6.0.6 on 2026-09-03 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_management', '0009_staffrequest_exceptional_absence'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffrequest',
            name='salary_deduction_status',
            field=models.CharField(choices=[('pending', 'A retirer'), ('withdrawn', 'Deja retire')], default='pending', help_text='Statut de suivi de la retenue salariale. Pending = a retirer, Withdrawn = deja retire.', max_length=20, verbose_name='Statut de la retenue salariale'),
        ),
    ]
