# Generated by Django 6.0.6 on 2026-07-23 21:04

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnel', '0004_annual_leave_window'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HREvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('family_event', 'Evenement familial'), ('medical_leave', 'Repos medical'), ('sick_absence', 'Absence maladie')], max_length=20, verbose_name="Type d'evenement")),
                ('status', models.CharField(choices=[('active', 'Actif'), ('cancelled', 'Annule')], default='active', max_length=20, verbose_name='Statut')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Date debut')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date fin')),
                ('days', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=6, verbose_name='Nombre de jours')),
                ('reason', models.TextField(blank=True, verbose_name='Motif / Observations')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise a jour')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_events_created', to=settings.AUTH_USER_MODEL, verbose_name='Cree par')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_events', to='personnel.employeeprofile', verbose_name='Employe')),
            ],
            options={
                'verbose_name': 'Evenement RH',
                'verbose_name_plural': 'Evenements RH',
                'ordering': ['-created_at'],
            },
        ),
    ]
