# Generated by Django 6.0.6 on 2026-07-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrevent',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure fin'),
        ),
        migrations.AddField(
            model_name='hrevent',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure debut'),
        ),
    ]
