# Generated by Django 6.0.6 on 2026-07-27 11:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_events', '0002_hrevent_end_time_hrevent_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrevent',
            name='days',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=6, verbose_name='Nombre de jours'),
        ),
    ]
