# Generated by Django 6.0.6 on 2026-07-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Centre ValBio', max_length=120)),
                ('subtitle', models.CharField(default='Centre International pour la Valorisation de la Biodiversite', max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.CharField(blank=True, max_length=255)),
                ('announcement', models.CharField(blank=True, help_text="Texte libre modifiable par l'admin pour annoncer un evenement.", max_length=255)),
                ('hero_image', models.FileField(blank=True, null=True, upload_to='branding/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Personnalisation connexion',
                'verbose_name_plural': 'Personnalisations connexion',
            },
        ),
    ]
