# Generated by Django 6.0.6 on 2026-07-01 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        ('requests_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loginbranding',
            name='logo_image',
            field=models.FileField(blank=True, null=True, upload_to='branding/logos/'),
        ),
        migrations.CreateModel(
            name='AccountActionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_username', models.CharField(max_length=150)),
                ('target_display_name', models.CharField(blank=True, max_length=255)),
                ('target_role', models.CharField(blank=True, max_length=20)),
                ('action', models.CharField(choices=[('created', 'Creation'), ('updated', 'Modification'), ('deleted', 'Suppression')], max_length=20)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_actions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_action_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique compte',
                'verbose_name_plural': 'Historiques comptes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestActionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approved', 'Approuvee'), ('rejected', 'Rejetee')], max_length=20)),
                ('previous_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_actions', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_history', to='requests_management.staffrequest')),
            ],
            options={
                'verbose_name': 'Historique demande',
                'verbose_name_plural': 'Historiques demandes',
                'ordering': ['-created_at'],
            },
        ),
    ]
