# Generated by Django 6.0.6 on 2026-07-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_loginbranding_logo_image_accountactionhistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginbranding',
            name='request_submission_email_enabled',
            field=models.BooleanField(default=True, help_text="Active l'envoi d'un email a l'adresse d'administration a chaque nouvelle demande."),
        ),
    ]
