# Generated by Django 6.0.6 on 2026-07-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_loginbranding_request_submission_email_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginbranding',
            name='request_submission_email_enabled',
            field=models.BooleanField(default=True, help_text="Active l'envoi d'un email a l'adresse de la Ressource Humain (RH) a chaque nouvelle demande."),
        ),
    ]
