# Generated by Django 6.0.6 on 2026-07-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_alter_loginbranding_request_submission_email_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginbranding',
            name='annual_leave_quota',
            field=models.DecimalField(decimal_places=1, default=30, help_text="Nombre de jours de conge acquis chaque année civile. Les droits de l'année en cours sont bloqués jusqu'à l'année suivante.", max_digits=6, verbose_name='Quota annuel de conge'),
        ),
    ]
