# Generated by Django 6.0.6 on 2026-07-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_annual_leave_quota'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginbranding',
            name='leave_rules',
            field=models.TextField(blank=True, default="Les droits de l'annee en cours (N) sont bloques jusqu'a l'annee suivante. La consommation s'effectue oldest-first (N-2 avant N-1).", help_text="Regles generales affichees dans l'interface de gestion des conges.", verbose_name='Regles generales de conges'),
        ),
        migrations.AddField(
            model_name='loginbranding',
            name='leave_window_size',
            field=models.PositiveIntegerField(default=3, help_text="Nombre d'annees conservees dans la fenetre glissante (ex: 3 = N-2, N-1, N).", verbose_name='Taille de la fenetre de conges'),
        ),
        migrations.AlterField(
            model_name='loginbranding',
            name='annual_leave_quota',
            field=models.DecimalField(decimal_places=1, default=30, help_text="Nombre de jours de conge acquis chaque annee civile. Les droits de l'annee en cours sont bloques jusqu'a l'annee suivante.", max_digits=6, verbose_name='Quota annuel de conge'),
        ),
    ]
