# Generated by Django 6.0.6 on 2026-08-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_loginbranding_leave_rules_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginbranding',
            name='recovery_annual_limit',
            field=models.DecimalField(decimal_places=1, default=15, help_text="Nombre maximum de jours de recuperation qu'un employe peut accumuler par annee.", max_digits=6, verbose_name='Limite annuelle de recuperation'),
        ),
        migrations.AddField(
            model_name='loginbranding',
            name='recovery_limit_enabled',
            field=models.BooleanField(default=True, help_text='Active ou desactive la limite annuelle de recuperation pour tous les employes.', verbose_name='Activer la limite annuelle des recuperations'),
        ),
    ]
