# Generated by Django 6.0.6 on 2026-08-20 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_loginbranding_recovery_annual_limit_and_more'),
        ('requests_management', '0008_staffrequest_recovery_consumption'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('priority', models.CharField(choices=[('info', 'Information'), ('warning', 'Attention'), ('important', 'Important')], default='info', max_length=20, verbose_name='Priorite')),
                ('notification_type', models.CharField(default='request_created', max_length=50, verbose_name='Type')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lue')),
                ('link_url', models.CharField(blank=True, max_length=500, verbose_name='Lien')),
                ('event_key', models.CharField(max_length=200, unique=True, verbose_name='Cle evenement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='requests_management.staffrequest')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='administrat_recipie_544db0_idx'), models.Index(fields=['recipient', '-created_at'], name='administrat_recipie_e495c2_idx')],
            },
        ),
    ]
