# Generated by Django 6.0.6 on 2026-08-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginbranding',
            name='profile_photo_editing_enabled',
            field=models.BooleanField(default=True, help_text='Active ou desactive la possibilite pour les employes de modifier leur photo de profil depuis leur interface.', verbose_name="Modification de la photo de profil par l'employe"),
        ),
    ]
