# Generated by Django 6.0.6 on 2026-09-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_loginbranding_profile_photo_editing_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginbranding',
            name='absence_annual_limit',
            field=models.DecimalField(decimal_places=1, default=15, help_text="Nombre maximum de jours d'absence qu'un employe peut accumuler par annee.", max_digits=6, verbose_name='Limite annuelle des absences'),
        ),
        migrations.AddField(
            model_name='loginbranding',
            name='absence_limit_enabled',
            field=models.BooleanField(default=False, help_text="Active ou desactive la limite annuelle d'absence pour tous les employes.", verbose_name='Activer la limite annuelle des absences'),
        ),
    ]
