# Generated by Django 6.0.6 on 2026-09-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_add_absence_limit_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginbranding',
            name='contact_enabled',
            field=models.BooleanField(default=True, help_text='Affiche ou masque les moyens de contact (WhatsApp, email, Telegram, etc.) sur la page de connexion.', verbose_name='Activer les moyens de contact sur la page de connexion'),
        ),
        migrations.AddField(
            model_name='loginbranding',
            name='email_contact',
            field=models.EmailField(blank=True, help_text='Adresse email utilisee pour le contact sur la page de connexion.', max_length=254, verbose_name='Adresse email de contact'),
        ),
        migrations.AddField(
            model_name='loginbranding',
            name='email_contact_enabled',
            field=models.BooleanField(default=False, help_text='Affiche le bouton de contact par email sur la page de connexion.', verbose_name='Afficher Email sur la page de connexion'),
        ),
        migrations.AddField(
            model_name='loginbranding',
            name='telegram_enabled',
            field=models.BooleanField(default=False, help_text='Affiche le bouton de contact Telegram sur la page de connexion.', verbose_name='Afficher Telegram sur la page de connexion'),
        ),
        migrations.AddField(
            model_name='loginbranding',
            name='telegram_id',
            field=models.CharField(blank=True, help_text='Identifiant Telegram (ex: @centrevalbio) ou lien complet.', max_length=100, verbose_name='Identifiant ou lien Telegram'),
        ),
        migrations.AddField(
            model_name='loginbranding',
            name='twitter_enabled',
            field=models.BooleanField(default=False, help_text='Affiche le bouton Twitter / X sur la page de connexion.', verbose_name='Afficher Twitter / X sur la page de connexion'),
        ),
        migrations.AddField(
            model_name='loginbranding',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='URL du profil Twitter / X (ex: https://x.com/centrevalbio).', verbose_name='Lien du profil Twitter / X'),
        ),
        migrations.AddField(
            model_name='loginbranding',
            name='whatsapp_enabled',
            field=models.BooleanField(default=True, help_text='Affiche le bouton de contact WhatsApp sur la page de connexion.', verbose_name='Afficher WhatsApp sur la page de connexion'),
        ),
        migrations.AddField(
            model_name='loginbranding',
            name='whatsapp_number',
            field=models.CharField(default='+261347794791', help_text='Numero WhatsApp au format international (ex: +261 34 77 947 91).', max_length=20, verbose_name='Numero WhatsApp'),
        ),
    ]
