# Generated by Django 6.0.6 on 2026-09-03 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_add_login_contact_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'INFO'), ('warning', 'WARNING'), ('error', 'ERROR'), ('critical', 'CRITICAL')], default='info', max_length=20, verbose_name='Niveau')),
                ('logger_name', models.CharField(blank=True, max_length=255, verbose_name='Logger')),
                ('message', models.TextField(verbose_name='Message')),
                ('user_display', models.CharField(blank=True, help_text="Nom d'utilisateur au moment du log (conservé meme si le compte est supprime).", max_length=255, verbose_name='Nom utilisateur (affichage)')),
                ('request_path', models.CharField(blank=True, max_length=500, verbose_name='URL')),
                ('request_method', models.CharField(blank=True, max_length=10, verbose_name='Methode')),
                ('request_ip', models.CharField(blank=True, max_length=45, verbose_name='Adresse IP')),
                ('error_id', models.CharField(blank=True, help_text="Identifiant unique d'erreur (format ERR-YYYYMMDD-HEX).", max_length=50, verbose_name='ID erreur')),
                ('exception_type', models.CharField(blank=True, max_length=255, verbose_name="Type d'exception")),
                ('traceback_data', models.TextField(blank=True, verbose_name='Traceback')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Donnees supplementaires')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date/heure')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_entries', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Entree de log',
                'verbose_name_plural': 'Entrees de log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='administrat_created_2605ef_idx'), models.Index(fields=['level'], name='administrat_level_4d86b4_idx'), models.Index(fields=['logger_name'], name='administrat_logger__c2e80f_idx'), models.Index(fields=['user_id'], name='administrat_user_id_175a9a_idx'), models.Index(fields=['error_id'], name='administrat_error_i_7528e4_idx'), models.Index(fields=['request_path'], name='administrat_request_a4133e_idx')],
            },
        ),
    ]
